readmeio/api

package.json

When I install and require the API package from my code, I get the following error:
```
internal/modules/cjs/loader.js:628
throw err;
^
Error: Cannot find module 'api'
```
I can get it working by simply setting the required path to `api/src/index.js`. This PR adds a main field, which will hopefully make this workaround moot.
Install the API package in a local directory and try requiring the dependency in a node script. You should see the aforementioned "module not found" error.
* I'm fixing a bug

fix(package.main): specify the entry point file

---

packages/httpsnippet-client-api/README.md
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

My work to add support for custom targets and clients to [HTTP Snippet](https://github.com/Kong/httpsnippet) was accepted, so this moves us off our fork and to that new version.
It also sets that version as a peer dependency so anytime this library is installed, it'll also require that the version of that library that supports it is also made aware to the user.

chore: moving off our httpsnippet fork and to v1.20.x

---

packages/api/__tests__/cache.test.js
packages/api/src/cache.js

This resolves a bug where relative paths in parent directories (`../openapi.json`, not `./openapi.json`) would not be able to be read.
Resolves https://github.com/readmeio/api/issues/61

fix: relative paths in parent parent directories not being supported

---

packages/api/__tests__/auth.test.js

This adds test cases to assert that the `.auth()` method does not need to be chained on top of an operation.
Resolves https://github.com/readmeio/api/issues/47

feat: adding test cases for supporting unchained auth usage

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/cache.js

We've had a bit of a falling out with the `yaml` package so we're moving to `js-yaml` as it's the more used package, and has a smaller smaller footprint.

chore(deps): swapping yaml for js-yaml

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-76.js
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-76/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-76/har.json
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/src/index.js

Resolves a bug where if an operation did not have an `operationId`, and the server URL had a path in it, that path would be included in the operation path on the snippet method.
Resolves #76

fix: snippet paths should not include the server url

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-78.js
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-78/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-78/har.json
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js

This resolves a bug where if an operation had path parameters, those path parameters wouldn't be present in code snippets.
Resolves #78

fix: bug where path params wouldn't be included in snippets

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-78-operationid.js
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-78-operationid/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-78-operationid/har.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-78/definition.json
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js

This fixes some more issues with the fix in #79 where path parameters would either not be added as metadata in code samples, or they be added in as metadata even if the evaluated path already contained them.

fix: issues where path params wouldn't always get added as metadata

---

packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

This will resolve a bug where server URLs with trailing slashes would be unable to be matched and throw errors when attempting to access the operation.
Resolves https://github.com/readmeio/api/issues/81
See https://github.com/readmeio/oas/pull/207/ for info and tests

chore(deps): upgrading @readme/oas-tooling to 3.4.7

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-76.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/petstore.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/query-auth.js
packages/httpsnippet-client-api/src/index.js

This breaks up the API snippets we're generating by breaking off the `sdk.auth()` call into a separate line.
Resolves https://github.com/readmeio/api-explorer/issues/823

feat: cleaning up api snippets by breaking off the auth call

---

package.json
packages/api/__tests__/index.test.js
packages/api/src/index.js

This updates the SDK so when error HTTP statuses (>=400, <=599) are hit, the promise is automatically rejected. 
It will turn the following, unnecessarily verbose code:
```js
readme
.auth(apiKey)
.createChangelog({ title, body: body.join('\n'), hidden: true })
.then(res => {
if (res.status !== 201) {
console.error('Error creating Changelog:', res.status, res.statusText);
process.exit(1);
}
return res.json();
})
.then(json => {
console.log('Changelog created!', json._id);
})
.catch(err => {
console.error(err);
process.exit(1);
});
```
Into the following:
```js
readme
.auth(apiKey)
.createChangelog({ title, body: body.join('\n'), hidden: true })
.then(res => res.json())
.then(json => {
console.log('Changelog created!', json._id);
})
.catch(err => {
console.error('Error creating Changelog:', …
```

feat: automatically reject the sdk promise for error statuses

---

packages/api/__tests__/cache-tmp.test.js
packages/api/package.json
packages/api/src/cache.js

This resolves #107 and edge case with the [find-cache-dir](https://www.npmjs.com/package/find-cache-dir) module where if it can't determine a cache directory, it'll return `undefined`. When this could crop up is if a user runs `npm install api` in a fresh directory without a `package.json` file. Since `find-cache-dir` looks for the root-most directory with a `package.json` file to determine where to put its `.cache/` directory into `node_modules/`, it can't.
So to account for this edge case, if we end up with an undefined cache directory from the module we'll instead fallback to creating a temp directory at the OS level.

fix: if no cache dir is determined, fallback to the os temp dir

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-128.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-76.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-78-operationid.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-78.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/petstore.js
packages/httpsnippet-client-api/__tests__/__fixtures__/output/query-auth.js
packages/httpsnippet-client-api/__tests__/__snapshots__/index.test.js.snap
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js

Fixes a bug in code snippets where a `Basic` auth header would remain encoded in the `.auth()` call and unable to be used properly when making a call. These auth heads are now being decoded and exploded into 1+ arguments for `.auth()` calls.
Fixes https://github.com/readmeio/api-explorer/issues/832

fix: basic auth headers now decoded and exploded into `.auth()` calls

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/issue-119.js
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-119/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-119/har.json
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/src/index.js

Adds support for the case where an `operationId` is not fully alphanumerical and thus can't be used as an object accessor.
Fixes https://github.com/readmeio/api/issues/119

fix: adding support for non-alphanumerical operation ids

---

packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/src/index.js

When an operation can't be found within the supplied `apiDefinition` we'd throw a fatal error on `operation.getSecurity()` not being a valid method because `operation` was null. This change cleans up that error to make it clearer what's happening.

fix: adding better messaging when operations can't be found

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/index.js
packages/api/src/lib/prepareAuth.js
packages/api/src/lib/prepareParams.js
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js

Upgrades `oas` and `@readme/oas-to-har` to their latest versions.

chore(deps): upgrade oas and oas-to-har

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
package.json
packages/api/package-lock.json
packages/api/package.json
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

* I added a new `getAuth` method into `Oas` (https://github.com/readmeio/oas/pull/376) but we've been unable to take advantage of it because we have some semver clases in ReadMe and it's preferring 10.0.0 over 10.2.0 because `httpsnippet-client-api` had 10.0.0 listed. Incredibly frustrating, but this should let us fully upgrade `oas` everywhere.

chore: update deps and require npm@7

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/full-many-query-params.js
packages/httpsnippet-client-api/__tests__/__fixtures__/request/application-json/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/full-many-query-params/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/full-many-query-params/har.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/full/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-128/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/issue-78/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/jsonObj-multiline/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/jsonObj-null-value/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/multipart-data/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/multipart-file/definition.json
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/src/index.js

Introduces some changes to snippet generation where if there are both `body` and `metadata` parameters, the inline character limit that we pass into [stringify-object](http://npm.im/stringify-object) gets cut in half so that they can both be presented in a cleaner syntax.

feat: cleaner snippets when body and metadata are present

---

.github/workflows/ci.yml
package.json
packages/api/package.json
packages/httpsnippet-client-api/package.json

Node 16 was released today and hits LTS in October so we should start building against it.

ci: allowing node 16 installs and builds

---

package-lock.json
packages/api/package-lock.json
packages/api/package.json
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

* docs: pull request template revisions ([c2946b3](https://github.com/readmeio/oas/commit/c2946b3))
* docs: updating the readme because it's out of date ([48514f7](https://github.com/readmeio/oas/commit/48514f7))
* feat: use null instead of empty-string for empty state (#451) ([b5ae66b](https://github.com/readmeio/oas/commit/b5ae66b)), closes [#451](https://github.com/readmeio/oas/issues/451)

chore(deps): upgrading `oas` to v13

---

packages/api/__tests__/index.test.js
packages/api/package-lock.json
packages/api/package.json

This upgrades `@readme/oas-to-har` to fix a quirk with query parameter handling where data is not being URL encoded before it's sent off to `fetch-har` to making a request.
See https://github.com/readmeio/oas-to-har/pull/16 for more details on the fix.
You can see this quirk in action right now against `main` by running the following snippet:
```js
const spec = {
servers: [
{ url: 'https://httpbin.org' }
],
paths: {
'/anything': {
get: {
parameters: [
{ name: 'pound', in: 'query' },
{ name: 'hash', in: 'query' },
{ name: 'array', in: 'query' },
{ name: 'weird', in: 'query' },
],
},
},
},
};
const sdk = require('./packages/api')(spec);
(async () => {
await sdk.get('/anything', {
pound: 'somethign&nothing=true',
hash: 'hash#data',
array: 'where[4]=10',
weird: 'properties["$email"] == …
```

fix: quirks in oas-to-har where query params are not being URI encoded

---

package-lock.json
packages/api/__tests__/lib/prepareParams.test.js
packages/api/package-lock.json
packages/api/package.json
packages/api/src/index.js
packages/api/src/lib/prepareParams.js
packages/api/src/lib/prepareServer.js
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js

* ~95% rewrite in Typescript
* A change in how core API definitions are stored on the main `Oas` class instance
* Heaps of new helpers methods and accessors
* Compatibility with `oas` v17.

feat: upgrading oas to v17

---

packages/httpsnippet-client-api/__tests__/__fixtures__/output/multipart-form-data-no-params.js
packages/httpsnippet-client-api/__tests__/__fixtures__/request/multipart-form-data-no-params/definition.json
packages/httpsnippet-client-api/__tests__/__fixtures__/request/multipart-form-data-no-params/har.json
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/src/index.js

Much like https://github.com/readmeio/httpsnippet/pull/65 this also fixes this case where a `multipart/form-data` HAR might not have `postData.params` present.

fix: crash where multipart/form-data requests dont have params

---

.github/workflows/ci.yml
package-lock.json
package.json
packages/api/package-lock.json
packages/api/package.json
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

Node 12 hits EOL status in April and we plan on immediately taking advantage of optional chaining, which Node 12 doesn't support, within #380 so we're dropping support for Node 12 now.
No testing needed, tests are just no longer being run on Node 12.

feat: dropping support for node 12

---

package-lock.json
packages/api/__tests__/cache.test.js
packages/api/__tests__/index.test.js
packages/api/package-lock.json
packages/api/package.json
packages/api/src/cache.js
packages/httpsnippet-client-api/__tests__/index.test.js
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

Our API can be accessed against `dash.readme.io` or `dash.readme.com`, but we prefer the latter.
Tests were updated and `@readme/oas-examples` was bumped to pull in our updated API definition with this server URL.

feat: changing the readme api url from .io to .com

---

packages/api/__tests__/index.test.ts
packages/api/src/index.ts

| 🚥  | 
| :-- |
This cleans up how we're extracting paths out of an API definition by using the `.getPaths()` accessor that `oas` offers.
All tests should still be passing

feat: cleaning up how we access paths out of the OAS

---

package-lock.json
packages/api/.eslintignore
packages/api/.eslintrc
packages/api/__tests__/dist.test.ts
packages/api/__tests__/tsconfig.json
packages/api/example.js
packages/api/package-lock.json
packages/api/package.json
packages/api/src/cache.ts
packages/api/src/index.ts
packages/api/src/package.ts
packages/api/src/typings.d.ts
packages/api/tsconfig.json

| 🚥  | Fix RM-3394 |
| :-- | :--- |
This rolls back the `target: es2020` config I added to our TS config when I migrated the library to TS as I didn't really understand the implications of what was going on with it.
The reason I added it in the first place was this error:
Because `form-data-encoder` uses `#private` class member declarations TS can only compile that to ES2015+ targets. Thankfully with TS 4.6 they're adding a new `node12` module and moduleResolution config that's able to ignore these at the expense of using types elsewhere. https://www.typescriptlang.org/tsconfig#node12nodenext-nightly-builds
And because `form-data-encoder` doesn't have a `@types/form-data-encoder` package we need to declare a module for it ourselves, resulting in type loss.
It's an unfortunate loss but …

fix: fixing how we generate the dist to work under CJS imports

---

package-lock.json
packages/api/package-lock.json
packages/api/package.json
packages/api/src/.sink.d.ts
packages/api/src/typings.d.ts
packages/api/tsconfig.json
packages/core/package-lock.json
packages/core/package.json
packages/core/tsconfig.json

Because the [form-data-encoder](https://npm.im/form-data-encoder) uses ES2015+ `#private` declarations for private class properties the only way we're able to compile that library into `api` is either by moving `api` to be ESM-only, by using the unstable `node12` module resolution that's only available in TS nightlies, or using the `skipLibCheck`  compiler option.
Because I don't want to make `api` ESM-only yet, and am very much uncomfortable running TS nightlies I figured out another solution: override `form-data-encoder` types with a `paths` declaration in `tsconfig.json` to map it to an empty module.
Volia the library compiles without any other special exclusions!

fix: moving us off the unstable node12 module resolution with a paths hack

---

packages/api/.eslintignore
packages/api/.gitignore
packages/api/.prettierignore
packages/api/package.json
packages/api/src/core/index.ts
packages/api/src/index.ts
packages/api/test/core/index.test.ts
packages/api/test/dist.test.ts
packages/api/tsconfig.json

This creates a new `APICore` class that can, and will, handle all API requests and fetching and parameter determination between `api` and the new codegen work.
This work was previously done in https://github.com/readmeio/api/pull/403 but as I'm decomissioning that branch I'm pulling the work there into `main` now.

feat: creation of a new APICore class to handle fetching

---

packages/api/src/core/parseResponse.ts

This is pulling over the work I did in https://github.com/readmeio/api/pull/418 into the `main` branch.
See https://github.com/readmeio/api/pull/418 more details.

fix: quirk with node 16 and `response.clone()`

---

packages/httpsnippet-client-api/.eslintignore
packages/httpsnippet-client-api/.prettierignore
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js
packages/httpsnippet-client-api/test/__datasets__/auth-apikey-cookie/har.json
packages/httpsnippet-client-api/test/__datasets__/auth-apikey-cookie/openapi.js
packages/httpsnippet-client-api/test/__datasets__/auth-apikey-cookie/output.js
packages/httpsnippet-client-api/test/__datasets__/full-many-query-params/har.json
packages/httpsnippet-client-api/test/__datasets__/full-many-query-params/output.js
packages/httpsnippet-client-api/test/__datasets__/full/har.json
packages/httpsnippet-client-api/test/__datasets__/full/output.js
packages/httpsnippet-client-api/test/index.test.js

| 🚥 Fix RM-3946 |
| :-- |
This adds support for both cookie auth and cookie parameters in `api` snippets. This work was previously added to `api` in #393 but, contrary to what that PR says, snippets have never supported it.

feat: adding support for cookies in snippets

---

package-lock.json
packages/api/.mocharc.json
packages/api/package-lock.json
packages/api/package.json
packages/api/src/codegen/typescript.ts
packages/api/test/__fixtures__/sdk/petstore/index.ts
packages/api/test/__fixtures__/sdk/readme/index.ts
packages/api/test/codegen/typescript.test.ts

| 🚥 Fix RM-3929 |
| :-- |
This refactors how we're generating TS types during codegen to never generate TS code for the same schema more than once. This work doesn't make a huge dent in the still slow codegen process, but it's an improvement for huge specs.
```
typescript generator
✔ should generate typescript code (3137ms)
✔ should be able to generate valid TS when a body is optional but metadata isnt (2056ms)
✔ should work against the petstore (17054ms)
✔ should work against our OAS (78918ms)
```
```
typescript generator
✔ should generate typescript code (4143ms)
✔ should be able to generate valid TS when a body is optional but metadata isnt (2323ms)
✔ should work against the petstore (16065ms)
✔ should work against our OAS (66688ms)
```

perf: codegen performance improvements

---

README.md
packages/api/README.md
packages/api/src/core/index.ts
packages/api/src/core/prepareAuth.ts
packages/api/src/index.ts
packages/api/test/auth.test.ts
packages/api/test/core/prepareAuth.test.ts

There's [a bug](https://github.com/readmeio/api/issues/102) with chaining auth calls due to the fact that we have a global state, and calling auth() again appends on to the state and breaks prepareAuth.
This PR removes the ability to call auth() in a chainable fashion, and only allows auth to be called at the top level.
I'd like to figure out a way to bring this back eventually, but the current API design doesn't support it in a clean way. We can revisit this when we look to support operations with multiple auth mechanisms.
This should probably be a major version bump due to removing functionality.
Fixes https://github.com/readmeio/api/issues/102
Does CI pass? 🟢

fix(auth): remove the ability to have auth chained with each request

---

package-lock.json
packages/api/package-lock.json
packages/api/package.json
packages/api/test/cli/codegen/languages/typescript.test.ts

The fork of `@apidevtools/json-schema-ref-parser` that `json-schema-to-typescript` switched over to in v11 is causing problems for us in Heroku installs so I'm downgrading it to v10 prior to when the fork was introduced in the hopes that this fixes things.
Thankfully the v11 upgrade didn't offer us much we can't live without for now but I'll keep an eye on that project for when the fork reference is removed from the package.

fix: downgrading json-schema-to-typescript to v10

---

packages/api/src/fetcher.ts
packages/api/test/fetcher.test.ts

| 🚥 Fix #481 |
| :-- |
This adds support to our core definition fetcher library to accept GitHub blob URLs like https://github.com/readmeio/oas-examples/blob/main/3.1/json/petstore.json and rewrite them to the raw version that we can access: https://raw.githubusercontent.com/readmeio/oas-examples/main/3.1/json/petstore.json
See tests.

feat: add support for github blob URLs

---

packages/api/src/cli/codegen/languages/typescript.ts
packages/api/test/__fixtures__/definitions/operationid-quirks.json
packages/api/test/__fixtures__/sdk/operationid-quirks/index.d.ts
packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
packages/api/test/__fixtures__/sdk/optional-payload/index.d.ts
packages/api/test/__fixtures__/sdk/optional-payload/index.ts
packages/api/test/__fixtures__/sdk/petstore/index.d.ts
packages/api/test/__fixtures__/sdk/petstore/index.ts
packages/api/test/__fixtures__/sdk/readme/index.d.ts
packages/api/test/__fixtures__/sdk/readme/index.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
packages/api/test/__fixtures__/sdk/simple-ts/index.d.ts
packages/api/test/__fixtures__/sdk/simple-ts/index.ts

While installing our OpenAPI definition to our homepage repository I noticed that all `get` accessors in the generated library had `path` typed to a simple `string` instead of the actual path in question. This fixes that!
With this work, autocompletion on HTTP method accessors should be a lot smarter and give you better inline docs:
See tests.

feat: improved typescript method accessor `path` type generation

---

.github/workflows/docs.yml
.gitignore
bin/build-markdown.js
docs/getting-started.md
package-lock.json
package.json

| 🚥 Fixes #486 |
| :-- |
This PR creates a lightweight docs build script using [`hercule`](https://github.com/jamesramsay/hercule) so we can reuse the content from `README.md` in `docs/getting-started.md`.
I ran the action locally in a dry run state using `act` and confirmed it works. I also [did a dry run in an actual GitHub Actions runner](https://github.com/readmeio/api/runs/7364020684?check_suite_focus=true#step:5:1) (see https://github.com/readmeio/api/pull/490/commits/87155425ad0dde478ca4c2a7db67d92e1fdf09d9) and confirmed that that looked good as well:
As you can see above, the contents of `getting-started.md` will be updated since it will now have the TOC from `README.md` in it.
I also confirmed in the debug logs that the content of `getting-started` is being populated correctly:

ci: getting started content reuse using hercule

---

package-lock.json
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.js
packages/httpsnippet-client-api/test/index.test.js

v4 of HTTPSnippet, and our fork, introduced a full TS rewrite that changed a handful of things around. This update `httpsnippet-client-api` to be compatible with everything that happened.

feat: updating httpsnippet-client-api to be compatible with httpsnippet v4

---

.prettierignore
docs/usage.md
packages/api/README.md
packages/api/src/cli/codegen/languages/typescript.ts
packages/api/test/__fixtures__/sdk/operationid-quirks/index.d.ts
packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
packages/api/test/__fixtures__/sdk/optional-payload/index.d.ts
packages/api/test/__fixtures__/sdk/optional-payload/index.ts
packages/api/test/__fixtures__/sdk/petstore/index.d.ts
packages/api/test/__fixtures__/sdk/petstore/index.ts
packages/api/test/__fixtures__/sdk/readme/index.d.ts
packages/api/test/__fixtures__/sdk/readme/index.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
packages/api/test/__fixtures__/sdk/simple-ts/index.d.ts
packages/api/test/__fixtures__/sdk/simple-ts/index.ts
packages/api/test/cli/codegen/languages/typescript.test.ts

```ts
import SDK from './packages/api/test__fixtures__/sdk/simple-ts';
const simpleSDK = new SDK();
simpleSDK.findPetsByStatus({ status: ['available'] }).then(res => {
console.log(res)
});
```
```ts
import simpleSDK from './packages/api/test__fixtures__/sdk/simple-ts';
simpleSDK.findPetsByStatus({ status: ['available'] }).then(res => {
console.log(res)
});
```
1. [`ts-morph`](https://npm.im/ts-morph) doesn't have great, or any really, support for programmatically creating an IFEE. You can create an IFEE with `addVariableStatement` but when attempting to export it with `setIsDefaultExport` `ts-morph` will crash.
2. After managing to get an IFEE compiled into `export default createSDK` and `module.exports = createSDK`, the `.d.ts` TS declaration files would break with a TS2309 error because …

fix: generated SDKs now ship an IFEE

---

package-lock.json
packages/api/package-lock.json
packages/api/package.json
packages/api/src/core/prepareParams.ts
packages/api/test/core/prepareParams.test.ts
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/__datasets__/headers/index.ts
packages/httpsnippet-client-api/test/__datasets__/headers/openapi.json
packages/httpsnippet-client-api/test/__datasets__/headers/output.js
packages/httpsnippet-client-api/test/__datasets__/petstore/output.js

feat: adding support for case-insensitive header parameters

---

packages/api/src/index.ts
packages/api/test/__fixtures__/definitions/operationid-quirks.json
packages/api/test/__fixtures__/sdk/operationid-quirks/index.d.ts
packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
packages/api/test/index.test.ts

This resolves a compatibility issue I introduced in v5 where because we now prefer cleaner, JS-method acessors to be used everywhere if you have an `operationId` that we deem to not be valid as a method accessor and clean it up, you can no longer use your original `operationId`.
For example if you have an operation that has `get-pet` as its `operationId` under v4 our code snippets would have you do this:
```js
await sdk['get-pet']().then(console.log);
```
In v5, and with our code snippets now in production we have you do this:
```js
await sdk.getPet().then(console.log);
```
If you upgrade from v4 to the v5 beta and have `sdk['get-pet']` we'll throw an error because though `get-pet` is in your spec we've rewritten it to be `getPet` and no longer recognize `get-pet`.
With this work here …

feat: allow original operationIDs to be used in dynamic SDKs

---

packages/api/README.md

The original example was failing with a `could not determine executable to run` error.

Fix example in README

---

package-lock.json
packages/api/package-lock.json
packages/api/package.json
packages/api/src/cli/codegen/languages/typescript.ts
packages/api/src/core/prepareParams.ts
packages/api/test/__fixtures__/definitions/response-title-quirks.json
packages/api/test/__fixtures__/sdk/response-title-quirks/index.d.ts
packages/api/test/__fixtures__/sdk/response-title-quirks/index.ts
packages/api/test/cli/codegen/languages/typescript.test.ts
packages/api/test/core/getJSONSchemaDefaults.test.ts
packages/httpsnippet-client-api/package-lock.json
packages/httpsnippet-client-api/package.json

| 🚥 Fix #523 |
| :-- |
A problem with `json-schema-to-typescript` was uncovered in https://github.com/readmeio/api/issues/523 where if a schema `title` prop starts with a number, that library will generate an invalid TypeScript interface causing codegen to fully crash out. To resolve this I've added a new `transformer` hook into [oas](https://npm.im/oas) in https://github.com/readmeio/oas/pull/695 to allow to adhoc transform these problematic to `json-schema-to-typescript` schemas into ones that can be used by prefixing them with an underscore. It's not a great solution but it's functional.
I've also upgraded all of our `oas`-related dependencies in the process as this change to `oas` to facilitate this new transformer incurred a breaking change there.
I've added a test case for one of …

fix: prefix schema titles that start with numbers to fix a type generation bug

---

packages/api/src/cli/codegen/languages/typescript.ts

Running `npx api install <something>` wouldn't install `@api/<something>` to your current working directory -- it would still at least create the SDK and install its own deps, just wouldn't link your root install up to it.

fix: bug where `@api/identifier` wasn't being installed properly

---

packages/api/src/cli/codegen/languages/typescript.ts
packages/api/test/cli/codegen/languages/typescript.test.ts

| 🚥 Fixes https://github.com/readmeio/api/issues/561 |
| :-- |
Not sure what happened but neither our tests assert that `npm install` in the root is installing the installed api, but the api isn't getting installed either.

fix: installs not actually installing the api

---

package-lock.json
packages/api/package-lock.json
packages/api/package.json
packages/api/src/cli/codegen/languages/typescript.ts
packages/api/test/cli/codegen/languages/typescript.test.ts
packages/httpsnippet-client-api/package-lock.json

| 🚥 https://github.com/readmeio/api/issues/560 |
| :-- |
This partially resolves an issue discovered in https://github.com/readmeio/api/issues/560 where because we aren't adding a `version` property into the `package.json` file we create for installed APIs Yarn has issues handling it.
We still don't fully support Yarn with this fix but it's a step towards doing so.

fix: compatibility with yarn installs where `package.json` needs `version`

---

packages/api/src/cli/codegen/languages/typescript.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts

| 🚥 Fixes #588 |
| :---------------- |
This is what using a CJS SDK looks like now:
What it looked like before (with `export default createSDK` in the `index.d.ts` file):

fix: resolving typing issues in JS codegen

---

packages/api/src/cli/commands/install.ts

When dependencies are not installed, the CLI prompts to install packages
This PR adds an `-y`/`--yes` flag that can be passed that acts as a `yes` input to the prompt.
N/A

feat: add install flag to bypass prompt

---

packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/__datasets__/parameter-special-characters/index.ts
packages/httpsnippet-client-api/test/__datasets__/parameter-special-characters/openapi.json
packages/httpsnippet-client-api/test/__datasets__/parameter-special-characters/output.js

| 🚥 Fixes CX-380 |
| :---------------- |
This fixes a quirk in snippet generation where if a path param in an OpenAPI definition had a hyphen like `app-id` then the snippet that we'd generate for this would be `appid`. This would cause these requests in `api` code to fail because `appid` is not a parameter that exists.

fix(snippet): bug where path params may lose hyphens if they have one

---

packages/api/src/cli/codegen/languages/typescript.ts
packages/api/src/core/errors/fetchError.ts
packages/api/src/core/index.ts
packages/api/test/__fixtures__/sdk/alby/index.ts
packages/api/test/__fixtures__/sdk/optional-payload/index.ts
packages/api/test/__fixtures__/sdk/petstore/index.ts
packages/api/test/__fixtures__/sdk/readme/index.ts

| 🚥 Fixes #612 |
| :---------------- |
This fixes a problem in codegen where we're documenting 400 and 500 status code families as being possible return types for SDK methods  which is not accurate as when we encounter these status codes we throw a `FetchError`. This is causing codegen's responses for these methods to effectively be typed as `unknown` as noted here[^1].
Unfortunately for us TypeScript doesn't offer any way to document that a method may throw an exception, and what that exception contains, so we need to fallback to a JSDoc `@throws` annotation. Not great but other than completely removing those error response types from the compiled SDK, which I don't want to do, we don't have any other option.
I have also cleaned up another very minor thing in this work with regard to …

fix(codegen): don't surface error responses as method return types

---

packages/api/src/core/prepareParams.ts
packages/api/test/__fixtures__/definitions/basiq.json
packages/api/test/core/prepareParams.test.ts
packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/__datasets__/full-many-query-params/index.ts
packages/httpsnippet-client-api/test/__datasets__/full-many-query-params/output.js
packages/httpsnippet-client-api/test/__datasets__/full/index.ts
packages/httpsnippet-client-api/test/__datasets__/full/output.js

| 🚥 Resolves #697 |
```js
const sdk = require('api')('@basiq/v3.0#edsvz2rlk7p46u2');
sdk.auth('Basic someAuthToken');
sdk.postToken({scope: 'CLIENT_ACCESS'}, {accept: 'application/json', 'basiq-version': '3.0'})
.then(({ data }) => console.log(data))
.catch(err => console.error(err));
```

fix: various quirks with how we handle `accept` headers

---

lerna.json
package-lock.json
package.json
packages/api/package.json
packages/api/src/codegen/languages/typescript.ts
packages/api/test/__fixtures__/sdk/alby/index.ts
packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
packages/api/test/__fixtures__/sdk/optional-payload/index.ts
packages/api/test/__fixtures__/sdk/petstore/index.ts
packages/api/test/__fixtures__/sdk/readme/index.ts
packages/api/test/__fixtures__/sdk/response-title-quirks/index.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
packages/api/test/__fixtures__/sdk/simple-ts/index.ts
packages/core/README.md
packages/core/package.json

| 🚥 Resolves ISSUE_ID |
Describe in detail what this PR is for.
Provide as much information as you can on how to test what you've done.

refactor: rename `@api/core` to `api.core`

---

package-lock.json
packages/api/package.json
packages/api/src/storage.ts

`make-dir` isn't needed a we can call` fs.makeDirSync` instead.

refactor: remove `make-dir` as a dep

---

packages/api/src/storage.ts
packages/api/test/storage.test.ts

Fixes a condition introduced in https://github.com/readmeio/api/pull/746 where `Storage.dir` would not get set properly when we create a new `.api/` directory.

fix(api): storage dir not being set properly

---

packages/api/src/codegen/codegenerator.ts
packages/api/src/codegen/factory.ts
packages/api/src/codegen/languages/typescript/index.ts
packages/api/src/commands/install.ts
packages/api/test/codegen/languages/typescript/index.test.ts
packages/api/test/codegen/languages/typescript/smoketest.test.ts

This is all some very minor internal API refactoring that spawned out of the ESM overhauls in https://github.com/readmeio/api/pull/754 that I decided to extract into a targeted changeset.

refactor(api): minor refactors to how some internal language classes are used

---

package-lock.json
packages/api/src/codegen/languages/typescript/index.ts
packages/api/test/__fixtures__/sdk/alby/package.json
packages/api/test/__fixtures__/sdk/alby/src/index.ts
packages/api/test/__fixtures__/sdk/operationid-quirks/package.json
packages/api/test/__fixtures__/sdk/operationid-quirks/src/index.ts
packages/api/test/__fixtures__/sdk/optional-payload/package.json
packages/api/test/__fixtures__/sdk/optional-payload/src/index.ts
packages/api/test/__fixtures__/sdk/petstore/package.json
packages/api/test/__fixtures__/sdk/petstore/src/index.ts
packages/api/test/__fixtures__/sdk/readme/package.json
packages/api/test/__fixtures__/sdk/readme/src/index.ts
packages/api/test/__fixtures__/sdk/response-title-quirks/package.json
packages/api/test/__fixtures__/sdk/response-title-quirks/src/index.ts
packages/api/test/__fixtures__/sdk/simple/package.json
packages/api/test/__fixtures__/sdk/simple/src/index.ts
packages/core/src/index.ts
packages/core/test/index.test.ts

Because `oas` is only used in codegen'd SDKs to do `Oas.init()` and supply an instance of `oas` to `@readme/api-core` we can lessen some steps, and a hard dependency on `oas` here by refactoring `@readme/api-core` to instead accept an API definition as its first argument.

refactor(core): removing `oas` as a dependency on codegen'd SDKs

---

packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/__datasets__/headers/index.ts
packages/httpsnippet-client-api/test/__datasets__/headers/openapi.json
packages/httpsnippet-client-api/test/__datasets__/headers/output.js

| 🚥 Resolves RM-8153 |
This fixes a quirk in `httpsnippet-client-api` where even though HTTP headers are case-insensitive the TS types we generate for `api` are not and we are currently lowercasing all non-reserved header names we add into code snippets.

fix(httpsnippet-client-api): retain casing for non-reserved headers

---

packages/api/src/codegen/languages/typescript/index.ts
packages/test-utils/sdks/alby/package.json
packages/test-utils/sdks/metrotransit/package.json
packages/test-utils/sdks/operationid-quirks/package.json
packages/test-utils/sdks/optional-payload/package.json
packages/test-utils/sdks/petstore/package.json
packages/test-utils/sdks/readme/package.json
packages/test-utils/sdks/response-title-quirks/package.json
packages/test-utils/sdks/simple/package.json
packages/test-utils/sdks/star-trek/package.json

| 🚥 Resolves RM-8187 |
For users who want to publish codegen'd SDKs to NPM I've added the `openapi.json` file that we add into them into the `files` array in `package.json`.

feat(api): exposing `openapi.json` to codegen'd `package.json` files

---

package-lock.json
packages/core/package.json
packages/core/src/lib/prepareParams.ts
packages/core/tsup.config.ts

Seeing the following error when attempting to run a codegen'd SDK via CJS:
```
/Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/node_modules/@readme/api-core/dist/chunk-TOMHUGQA.cjs:138
var _getstream = require('get-stream');
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/node_modules/get-stream/source/index.js from /Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/node_modules/@readme/api-core/dist/chunk-TOMHUGQA.cjs not supported.
Instead change the require of index.js in /Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/node_modules/@readme/api-core/dist/chunk-TOMHUGQA.cjs to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (/Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/node_modules/@readme/api-core …
```

fix(cjs): include get-stream directly in bundle

---

.gitignore
package-lock.json
packages/api/package.json
packages/api/schema.json
packages/api/src/storage.ts
packages/api/test/storage.test.ts

| 🚥 Resolves RM-8186 |
This adds a new `$schema` property to the `api.json` lockfiles we generate when installing an API.
Here it is validating:
And what it looks like after instaling an API[^1]:

feat(api): adding a `$schema` property to generated `api.json` lockfiles

---

package-lock.json
packages/api/package.json
packages/api/schema.json
packages/api/src/commands/index.ts
packages/api/src/commands/list.ts
packages/api/src/storage.ts
packages/api/test/storage.test.ts

| 🚥 Resolves RM-4124 |
This introduces a new `list` command for listing out any API SDKs that you may have installed.
```
Usage: api list|ls [options]
list any installed API SDKs
Options:
-h, --help  display help for command
```
Additionally I've also added a couple new things into the lockfile:
We're also removing `version` from the lockfile in favor of the recently added `$schema` property. Having two versioned fields in the lockfile felt like too much complexity.
Here's what it all looks like:
And if you don't have any APIs installed:

feat(api): creation of a new `list` command

---

.github/workflows/ci.yml
packages/api/package.json

Node v18 is bundled with npm@9 so we don't need to install it ourselves. Also did a little bit of other cleanup in our `package.json` scripts etc.

ci: cleanup

---

packages/api/src/codegen/languages/typescript/index.ts

We should presumably make it this:
```json
"@readme/api-core": "^7.0.0-beta.0"
```
instead of this:
```json
"@readme/api-core": "7.0.0-beta.0"
```

fix: add caret to package.json dep

---

packages/api/src/codegen/languages/typescript/index.ts
packages/core/package.json
packages/core/src/index.ts
packages/core/src/types.ts
packages/core/tsup.config.ts
packages/test-utils/sdks/alby/src/index.ts
packages/test-utils/sdks/metrotransit/src/index.ts
packages/test-utils/sdks/operationid-quirks/src/index.ts
packages/test-utils/sdks/optional-payload/src/index.ts
packages/test-utils/sdks/petstore/src/index.ts
packages/test-utils/sdks/readme/src/index.ts
packages/test-utils/sdks/response-title-quirks/src/index.ts
packages/test-utils/sdks/simple/src/index.ts
packages/test-utils/sdks/star-trek/src/index.ts

We've got a weird issue in the `api@next` dist where the `json-schema-to-ts` refactor I did in https://github.com/readmeio/api/pull/764 is mucking up some types. I'm not totally sure why!
`.cjs`, `.mts`, and `.ts` generated SDK:
However a `.mjs` and `.js` file have the types completely different:
While debugging why this was happening I noticed that `attw` was reporting that the types for `core` were all messed up:
After refactoring `ConfigOptions`, `FetchResponse` and `HTTPMethodRange` types into a new `@readme/api-core/types` file `attw` is now happy:

fix(core): funky type issues with the main export exporting multiple things

---

package-lock.json
packages/api/package.json
packages/api/src/commands/install.ts
packages/api/src/lib/suggestedOperations.ts
packages/api/test/lib/__snapshots__/suggestedOperations.test.ts.snap
packages/api/test/lib/suggestedOperations.test.ts
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/index.test.ts

| 🚥 Resolves RM-8185 |
This work is some QOL improvements to the post-installation screen where we'll now, using a very simple algorithm to determine the best endpoint for a demo[^1], show a code example to folks so they can immediately get started with their newly generated SDK. Here's what it looks like:
And in the case of us not being able to find a good endpoint to demo[^2] we just won't show a code example:
[^1]: With the exception of us being able to handle auth examples, this algorithm is the same that powers the "recommended" API endpoint section of ReadMe Realtime configuration.
[^2]: In this case this API definition was only comprised endpoints with path parameters.

feat(api): improvements to the installation screen

---

.github/workflows/smoketest.yml
packages/api/test/codegen/languages/typescript/smoketest.test.ts

This fixes a problem in our Smoketest suite that arose with the migration to Vitest where we are no longer able to pass custom arguments to unit test calls.
https://github.com/readmeio/api/actions/workflows/smoketest.yml
The smoketest suite has been broken for 8 months. It runs once a week and I've just been ignoring the failures. 🙃

ci(api): fixing our smoketest suite

---

package-lock.json
packages/api/package.json
packages/api/src/lib/suggestedOperations.ts
packages/core/src/index.ts
packages/core/src/lib/prepareAuth.ts

Slightly refactors the work I did in https://github.com/readmeio/api/pull/783 to remove our dependency on `@readme/oas-to-har` in `api`. Because we already depend on this library in core it's easier to have a method for generating a HAR object from the spec we're using there instead of having `oas-to-har` as a full dependency in `api`.
Proof that this all still works:

refactor(api): refactor core to handle HAR generation for code snippets

---

package-lock.json
packages/api/src/lib/suggestedOperations.ts
packages/httpsnippet-client-api/README.md
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/index.test.ts

With the work I did in https://github.com/readmeio/httpsnippet/releases/tag/8.1.0 this slightly refactors[^1] `httpsnippet-client-api` to now be a proper new HTTPSnippet plugin so it can now be installed as a one-liner:
```js
import { HTTPSnippet, addClientPlugin } from '@readme/httpsnippet';
import plugin from 'httpsnippet-client-api';
addClientPlugin(plugin);
```
Previously the way it was installed was as such:
```js
import { HTTPSnippet, addTargetClient } from '@readme/httpsnippet';
import plugin from 'httpsnippet-client-api';
addTargetClient('node', plugin);
```
This plugin refactor allows us to move the target that we're targeting, `node`, directly onto the client plugin. This refactor, and the addition of an `installation` message on the client will allow us to do some fun stuff in …

refactor(snippets): moving the library over to be an HTTPSnippet plugin

---

packages/api/src/codegen/languages/typescript/index.ts
packages/test-utils/sdks/alby/package.json
packages/test-utils/sdks/metrotransit/package.json
packages/test-utils/sdks/operationid-quirks/package.json
packages/test-utils/sdks/optional-payload/package.json
packages/test-utils/sdks/petstore/package.json
packages/test-utils/sdks/readme/package.json
packages/test-utils/sdks/response-title-quirks/package.json
packages/test-utils/sdks/simple/package.json
packages/test-utils/sdks/star-trek/package.json

The `prepare` script that was added to codegen'd `package.json` files in https://github.com/readmeio/api/pull/761 is being executed when we install that SDK resulting us in running the compilation step twice. Because I'd like to keep the dependency installation and SDK dist compilation processes separate we should run `npm install` with the `--ignore-scripts` option.
fixes RM-8243

fix(api): run `npm install` with `--ignore-scripts`

---

packages/api/src/codegen/languages/typescript/index.ts
packages/test-utils/sdks/alby/package.json
packages/test-utils/sdks/metrotransit/package.json
packages/test-utils/sdks/operationid-quirks/package.json
packages/test-utils/sdks/optional-payload/package.json
packages/test-utils/sdks/petstore/package.json
packages/test-utils/sdks/readme/package.json
packages/test-utils/sdks/response-title-quirks/package.json
packages/test-utils/sdks/simple/package.json
packages/test-utils/sdks/star-trek/package.json

This updates our codegen'd SDKs so their `package.json` files now surface the `package.json` in the `exports` object. Why? I still don't exactly know, but it feels like a safe convention to follow in lieu of an actual spec around this ¯\_(ツ)_/¯
I thought about also adding [`sideEffects: false`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) the way we do in other places but I think the SDK might need to be set to `type: module` first?

feat(codegen): expose `package.json` in `exports` object

---

packages/api/.gitignore
packages/api/legacy-require-handler.cjs
packages/api/legacy-require-handler.d.cts
packages/api/package.json

| 🚥 Resolves RM-8241 |
If users were to try and use the `const sdk = require("api")("url");` pattern that has since been removed from `api` v7, they'll see a confusing error like this:
```
node:internal/modules/cjs/loader:1080
throw err;
^
Error: Cannot find module 'api'
Require stack:
- /Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/src/legacy-require.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
at Module._load (node:internal/modules/cjs/loader:922:27)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Users/kanadg/Code/readmeio/tmp-api-tsup-sandbox/src/legacy-require.js:1:17)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at …
```

feat: throw error for legacy dynamic `require` users

---

package-lock.json
packages/core/tsup.config.ts
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/tsup.config.ts

`camelcase` and `stringify-object` being ESM only is causing issues with loading `httpsnippet-client-api` in CJS environments. This work moves them to now being compiled into our dist.

fix(httpsnippet-client-api): making external deps no longer external

---

packages/api/src/codegen/languages/typescript/index.ts
packages/test-utils/sdks/alby/src/types.ts
packages/test-utils/sdks/metrotransit/src/types.ts
packages/test-utils/sdks/optional-payload/src/types.ts
packages/test-utils/sdks/petstore/src/types.ts
packages/test-utils/sdks/readme/src/types.ts
packages/test-utils/sdks/response-title-quirks/src/types.ts
packages/test-utils/sdks/simple/src/types.ts
packages/test-utils/sdks/star-trek/src/types.ts

Because all of the schemas that we're importing in codegen'd `types.ts` files are for types only we can import them explicitly as types.

feat(api): import schemas in the types file as types

---

package-lock.json
packages/api/package.json
packages/api/src/bin.ts
packages/api/src/lib/isCI.ts
packages/api/src/lib/prompt.ts

| 🚥 Resolves RM-8193 |
This PR rips a couple pages from the `rdme` playbook:
The `update-notifier` changes are minimal enough and the package is weird enough where it's not particularly easy nor worth it to QA, but I confirmed that the CLI still works!
As for the prompt handler changes, you can check out this branch and try running the following command:
```sh
CI=true npm run debug:bin install https://raw.githubusercontent.com/readmeio/oas-examples/main/3.0/json/petstore-simple.json
```
It should error out with an output like this:
```
> api@7.0.0-beta.4 debug:bin
> NODE_OPTIONS=--no-warnings node --loader ts-node/esm src/bin.ts install https://raw.githubusercontent.com/readmeio/oas-examples/main/3.0/json/petstore-simple.json
- Fetching your API definition
✔ …
```

feat(api): small CLI quality-of-life changes

---

packages/test-utils/tsconfig.json
tsconfig.base.json

I've done cursory checks in the past to make sure our generated SDKs meet the requirements of TS strict mode, but it just occurred to me that we're not doing any type-checking in our tests, so this PR enables that. Glad to report that the SDKs passed with flying colors ✨
Do tests still pass?

test: run `tsc` on SDK fixtures

---

packages/core/src/lib/parseResponse.ts
packages/core/test/lib/parseResponse.test.ts

| 🚥 Resolves ISSUE_ID |
- Avoid mutating the response object when calling `response.text()`. This can be helpful if we want to consume the response in a different way, like `response.arrayBuffer()` when working with files
- With this change, the original response object is returned.

feat: avoid modifying the response object when calling response.text()

---

packages/core/src/lib/prepareServer.ts

| 🚥 Resolves ISSUE_ID |
A truthy check was being performed on the `serverIdx`, which would effectively ignore the value when `serverIdx` was 0.
This fixes that to ensure that server variables are respected when the server URL passed in is the same as the server URL defined in the OAS.
It now works for us, whereas it didn't before.

fix: ensure prepareServer respects server variables when custom url is the same as the OAS url

---

packages/api/README.md

| 🚥 Resolves ISSUE_ID |
After "npx api install" the dependecy "@api/gkmmk":"file:.api/apis/gkmmk" was created, but not "api": "file:.api/apis/gkmmk"
for ESM
I haven't tested the package fully, but I thought I'd point it out, because the way from the readme doesn't work for me

fix: package name for ESM syntax

---

package-lock.json
package.json
packages/api/package.json
packages/core/package.json
packages/httpsnippet-client-api/package.json
packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/index.test.ts

Bumps a bunch of outdated dependencies, and fixes up the type on the client plugin in `httpsnippet-client-api`.
**Before**
```
Package                Current  Wanted  Latest  Location                               Depended by
@readme/eslint-config   13.5.1  13.5.2  14.0.0  node_modules/@readme/eslint-config     api
@readme/httpsnippet      8.1.2  10.0.0  10.0.0  node_modules/@readme/httpsnippet       httpsnippet-client-api@7.0.0-beta.5
@readme/oas-to-har      23.2.1  23.2.4  23.2.4  node_modules/@readme/oas-to-har        core@npm:@readme/api-core@7.0.0-beta.5
ajv-formats              2.1.1   2.1.1   3.0.1  node_modules/ajv-formats               api@7.0.0-beta.5
commander               11.1.0  11.1.0  12.0.0  node_modules/commander                 api@7.0.0-beta.5
eslint …
```

chore: bump deps, fix types

---

packages/httpsnippet-client-api/src/index.ts
packages/httpsnippet-client-api/test/index.test.ts

Running `npx api install @handbook/v1.0#fzmso1cluu0vbwv` on a Zsh environment breaks because the hash there sends Zsh into a tizzy. Wrapping our registry identifiers for `api` in quotes fixes this.

fix: zsh compatibility for `api` installation instructions

---

packages/api/bin/buildVersionedFiles.ts
packages/api/package.json
packages/api/src/codegen/languages/typescript/index.ts
packages/api/test/storage.test.ts

| 🚥 Resolves #950 |
<sub>(PR description stolen from https://github.com/readmeio/rdme/pull/993)</sub>
TC39 updated their import _assertions_ to be import _attributes_ and it's a bit of a mess now that we're running tests against Node v22.
Here's what importing JSON in ESM used to look like:
```js
import { x } from "./mod" assert { type: "json" }
```
now it looks like this:
```js
import { x } from "./mod" with { type: "json" };
```
Support for this new `with` keyword was added in [Node v18.20.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#added-support-for-import-attributes) and [Node v20.10.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-11-22-version-20100-iron-lts-targos) (and is supported on all v21 …

fix: use correct import attributes syntax

---

package-lock.json
packages/api/package.json
packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
packages/httpsnippet-client-api/package.json

Upgrades `oas@20` in our v6 release series to resolve a security vulnerability in its dependency upon [jsonpath-plus](https://github.com/readmeio/oas/pull/942).
This will resolve https://github.com/readmeio/api/issues/969.

fix(v6): upgrading `oas` to resolve some security vulnerabilities

---

.github/workflows/ci.yml
package-lock.json
package.json
packages/api/package.json
packages/core/package.json
packages/httpsnippet-client-api/package.json

This bundles `attw` into our build processes for ensuring that the types and exports we're defining in our `package.json` files are usable under a variety of different Node resolution systems.

ci: running `attw` along our test suite

---

package-lock.json
packages/httpsnippet-client-api/package.json

I published a new major version of `oas` today and am having a real hard time getting it installed in our monorepo thanks to the peerdep for `oas@27` that exists in `httpsnippet-client-api`. Moving it to a normal dependency should resolve my woes.

chore: moving the `oas` dep in `httpsnippet-client-api` off a peerDep
